# Generated by Django 4.1 on 2023-10-16 17:06

import consumer.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "cellphone",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="cellphone"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "avarte",
                    models.ImageField(
                        default="image/default/E23A1F.jpg",
                        upload_to=consumer.models.user_img_path,
                        verbose_name="avarte",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="是否激活", verbose_name="active"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        blank=True, max_length=50, verbose_name="abstract"
                    ),
                ),
            ],
            options={
                "verbose_name": "t_cosumer",
                "verbose_name_plural": "t_cosumers",
                "db_table": "t_cosumer",
                "ordering": ("id", "date_joined"),
            },
        ),
    ]
