# Generated by Django 4.1 on 2023-07-08 15:14

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="consumer",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
