# Generated by Django 4.1 on 2023-07-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0002_alter_consumer_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consumer",
            options={
                "ordering": ("id", "date_joined"),
                "verbose_name": "t_cosumer",
                "verbose_name_plural": "t_cosumers",
            },
        ),
        migrations.AlterModelTable(
            name="consumer",
            table="t_cosumer",
        ),
    ]
