# Generated by Django 4.1 on 2023-07-12 00:54

import consumer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0003_alter_consumer_options_alter_consumer_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumer",
            name="avarte",
            field=models.ImageField(
                default="image/default/E23A1F.jpg",
                height_field="200",
                upload_to=consumer.models.user_img_path,
                verbose_name="avarte",
                width_field="200",
            ),
        ),
    ]
