# Generated by Django 4.1 on 2023-07-12 06:37

import consumer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0004_consumer_avarte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumer",
            name="avarte",
            field=models.ImageField(
                default="image/default/E23A1F.jpg",
                upload_to=consumer.models.user_img_path,
                verbose_name="avarte",
            ),
        ),
    ]
