# Generated by Django 4.1 on 2023-07-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0005_alter_consumer_avarte"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumer",
            name="cellphone",
            field=models.CharField(
                default=1, max_length=150, unique=True, verbose_name="cellphone"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="consumer",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
