# Generated by Django 4.1 on 2023-07-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0007_alter_consumer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumer",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
