# Generated by Django 4.1 on 2023-07-08 13:22

import article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("digest", models.TextField(max_length=128)),
                (
                    "cover",
                    models.ImageField(
                        default="article/default/default.png",
                        upload_to=article.models.article_img_path,
                    ),
                ),
                ("body", models.TextField()),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("tags", models.JSONField(verbose_name="标签")),
                (
                    "status",
                    models.CharField(
                        choices=[("original", "原创"), ("draft", "草稿"), ("reship", "转载")],
                        default="draft",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                ("upvote", models.PositiveIntegerField(default=0, help_text="点赞量")),
                ("collect", models.PositiveIntegerField(default=0, help_text="收藏量")),
                ("pageviews", models.PositiveIntegerField(default=0, help_text="阅读量")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
                "db_table": "article",
                "ordering": ("id", "author", "date_create"),
            },
        ),
    ]
