# Generated by Django 4.1 on 2023-07-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0001_initial"),
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="consumer.consumer",
                to_field="username",
            ),
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("body", models.TextField()),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consumer.consumer",
                        to_field="username",
                    ),
                ),
            ],
            options={
                "verbose_name": "t_draft",
                "verbose_name_plural": "t_drafts",
                "db_table": "t_draft",
                "ordering": ("id", "author", "date_create"),
            },
        ),
    ]
