# Generated by Django 4.1 on 2023-07-12 00:54

import article.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0004_consumer_avarte"),
        ("article", "0002_alter_article_author_draft"),
    ]

    operations = [
        migrations.CreateModel(
            name="Original",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("digest", models.TextField(max_length=128)),
                (
                    "cover",
                    models.ImageField(
                        default="article/default/default.png",
                        upload_to=article.models.article_img_path,
                    ),
                ),
                ("body", models.TextField()),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("tags", models.JSONField(verbose_name="标签")),
                ("upvote", models.PositiveIntegerField(default=0, help_text="点赞量")),
                ("collect", models.PositiveIntegerField(default=0, help_text="收藏量")),
                ("pageviews", models.PositiveIntegerField(default=0, help_text="阅读量")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consumer.consumer",
                        to_field="username",
                    ),
                ),
            ],
            options={
                "verbose_name": "Original",
                "verbose_name_plural": "Originals",
                "db_table": "Original",
                "ordering": ("id", "author"),
            },
        ),
    ]
