# Generated by Django 4.1 on 2023-07-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_original"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="original",
            options={
                "ordering": ("id", "author"),
                "verbose_name": "t_original",
                "verbose_name_plural": "t_originals",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[("or", "原创"), ("dr", "草稿")],
                default="draft",
                max_length=50,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(default="无标题", max_length=64),
        ),
        migrations.AlterModelTable(
            name="original",
            table="t_original",
        ),
        migrations.DeleteModel(
            name="Draft",
        ),
    ]
