# Generated by Django 4.1 on 2023-07-13 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0006_consumer_cellphone_alter_consumer_email"),
        ("article", "0004_alter_original_options_alter_article_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ("id", "author", "date_create"),
                "verbose_name": "t_article",
                "verbose_name_plural": "t_articles",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                db_column="author",
                on_delete=django.db.models.deletion.CASCADE,
                to="consumer.consumer",
                to_field="username",
            ),
        ),
        migrations.AlterModelTable(
            name="article",
            table="t_article",
        ),
    ]
