# Generated by Django 4.1 on 2023-07-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Token",
        ),
    ]
