# Generated by Django 4.1 on 2023-07-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="token",
            options={
                "ordering": ("user", "created"),
                "verbose_name": "t_token",
                "verbose_name_plural": "t_tokens",
            },
        ),
    ]
