# Generated by Django 4.1 on 2023-07-14 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0006_consumer_cellphone_alter_consumer_email"),
        ("auths", "0004_alter_token_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="consumer.consumer",
                verbose_name="User",
            ),
        ),
    ]
